Dockerfile, pom.xml
Updated references to mod-orders in the pom and Docker file to mod-orders-storage.  This will complete the renaming of the repo.
=> updated 'mod-orders' to 'mod-orders-storage' in pom and Dockerfile

NEWS.md, pom.xml
This is somewhat confusing/mysterious... the fix that prompted this hotfix release was actually made las Friday (12/7), committed to the release-1.0.1 branch, and merged back into the master branch.
Version 1.0.1 was created and released from the release-1.0.1 branch the following Monday (12/10), but somehow did not include the hotfix.  However, when looking at the release-1.0.1 branch it's there...  Not sure what happened; I didn't perform the release and I don't immediately see anything that explains this in the git history.
Anyway, I created a release-1.0.2 branch from release-1.0.1, updated the news and cut a new release (v1.0.2).  This resulting PR that needs to get merged into master only contains the changes to the NEWS file since as I mentioned before the "hotfix" was already …
=> Release 1.0.2

ramls/orders.raml, src/main/java/org/folio/rest/impl/OrdersAPI.java, src/test/java/org/folio/rest/impl/POsTest.java
Fixing [MODORDSTOR-36](https://issues.folio.org/browse/MODORDSTOR-36)
Renaming `/orders-storage/orders` back to `/orders` until proper support added with MODORDSTOR-22 implementation when `/orders` is moved back to `mod-orders`
=> MODORDSTOR-36 Rolling back `/orders` endpoint

NEWS.md, pom.xml, ramls/adjustment.raml, ramls/alert.raml, ramls/claim.raml, ramls/cost.raml, ramls/details.raml, ramls/eresource.raml, ramls/fund_distribution.raml, ramls/license.raml, ramls/location.raml, ramls/physical.raml, ramls/po_line.raml, ramls/purchase_order.raml, ramls/reporting_code.raml, ramls/source.raml, ramls/vendor_detail.raml
See [MODORDSTOR-43](https://issues.folio.org/browse/MODORDSTOR-43)
This is a follow-on release to fix the RAML so that the API version is consistent with that specified in the module descriptor.
Push button, turn crank, voila! New and improved.
=> MODORDSTOR-43 - Release 2.0.1

NEWS.md, pom.xml
A patch release is required to address a critical problem: [MODORDSTOR-44](https://issues.folio.org/browse/MODORDSTOR-44)
NOTE:  it looks like the removal of `po_line_workflow_status` snuck into this branch as well, but that shouldn't be a big deal.
Merge the MODORDSTOR-44 branch into the release-2.0.1 branch and cut a new release (2.0.2)
=> Release 2.0.2

src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/POsTest.java, src/test/resources/purchase_order.sample
In order to guarantee PO number uniqueness across all orders a unique constraint needs to be added for PO number filed in DB
https://issues.folio.org/browse/MODORDSTOR-42
Adding unique index in database creation snippet
=> MODORDSTOR-42 unique index for po_number

PULL_REQUEST_TEMPLATE.md
In order to reduce the chance of breaking the nightly folio-testing build by merging breaking changes to master, we need to be more careful and consider the wider impact of the merge.
Add a pre-merge checklist to the PR template.  Ideally the assignee of the PR will quickly go through the checklist before merging.
=> Add Pre-Merge Checklist to PR Template

src/main/resources/data/purchase_orders/14383007_ongoing_open.json, src/main/resources/data/purchase_orders/268758_one-time_open.json, src/main/resources/data/purchase_orders/268879_one-time_closed.json, src/main/resources/data/purchase_orders/306251_one-time_closed.json, src/main/resources/data/purchase_orders/306857_ongoing_open.json, src/main/resources/data/purchase_orders/312325_one-time_open.json, src/main/resources/data/purchase_orders/313000_one-time_open.json, src/main/resources/data/purchase_orders/36547_one_time_closed.json, src/main/resources/data/purchase_orders/S60402_ongoing_closed.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/POsTest.java, src/test/java/org/folio/rest/impl/ReceivingHistoryTest.java, src/test/resources/po_line.sample, src/test/resources/po_line_for_view.sample, src/test/resources/purchase_order.sample, src/test/resources/purchase_order_for_view.sample
[MODORDSTOR-51](https://issues.folio.org/browse/MODORDSTOR-51) Add 'purchase_order_id' and "dateOrdered" to the receiving_history_view
- added 'purchase_order_id'  and 'dateOrdered' to the receiving_history_view with [folio-org/acq-models#84](https://github.com/folio-org/acq-models/pull/84)
- updated sample data, including for [MODORDERS-147](https://issues.folio.org/browse/MODORDERS-147)
- updated receiving_history_view creation snippet
- unit tests are updated to test the functionality
- Does this PR meet or exceed the expected quality standards ([sonar PR#80](https://sonarcloud.io/project/issues?id=org.folio%3Amod-orders-storage&pullRequest=80&resolved=false))?
- Does this introduce breaking …
=> MODORDSTOR-51 Add 'purchase_order_id' and "dateOrdered" to the receiving_history_view

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/adjustment.raml, ramls/alert.raml, ramls/claim.raml, ramls/cost.raml, ramls/details.raml, ramls/eresource.raml, ramls/fund_distribution.raml, ramls/license.raml, ramls/location.raml, ramls/orders.raml, ramls/physical.raml, ramls/pieces.raml, ramls/po_line.raml, ramls/po_number.raml, ramls/purchase_order.raml, ramls/receiving_history.raml, ramls/reporting_code.raml, ramls/source.raml, ramls/vendor_detail.raml
[MODORDSTOR-56](https://issues.folio.org/browse/MODORDSTOR-56) Create release v3.0.0
- The major version of the interfaces and ramls increased because of the changes done in scope of [MODORDSTOR-46](https://issues.folio.org/browse/MODORDSTOR-46), [MODORDSTOR-53](https://issues.folio.org/browse/MODORDSTOR-53) and [MODORDSTOR-55](https://issues.folio.org/browse/MODORDSTOR-55)
- News file is updates
=> Release 3.0.0

README.md, ramls/orders.raml, ramls/pieces.raml, ramls/po-line-number.raml, ramls/po-line.raml, ramls/po-number.raml, ramls/purchase-order.raml, ramls/receiving-history.raml
Clearly document that the mod-orders-storage APIs are intended for internal use only.  When applicable, suggest an appropriate API to use instead.
Add notes to the README and RAML files
=> Document that this module is intended for internal use only.

pom.xml, src/main/java/org/folio/rest/persist/HelperUtils.java, src/test/java/org/folio/rest/impl/HelperUtilsTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java
PowerMockito included for covering failed API paths in PR [#102](https://github.com/folio-org/mod-orders-storage/pull/102).
=> MODORDSTOR-22 - Implement GET /orders w/ search and filtering

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/orders.raml, ramls/pieces.raml, ramls/po-line.raml, ramls/purchase-order.raml, ramls/receiving-history.raml
[MODORDSTOR-72](https://issues.folio.org/browse/MODORDSTOR-72) - Release 5.0.0
- Preparing News
- Increase following interface versions due to non-backward compatible changes
- `orders-storage.pieces`
- `orders-storage.po-lines`
- `orders-storage.purchase-orders`
- `orders-storage.receiving-history`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> MODORDSTOR-72 - Release 5.0.0

src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
Fix an error that occurs when rerunning tests folio-org/folio-api-tests#182.
- closing DB connection on DELETE /_/tenant …
=> MODORDERS-233 Add tenantId to cache keys

src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/po-lines/101113-1_pending_physical.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/14383007-1_pending_physical_gift.json, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306251-1_pending_electronic.json, src/main/resources/data/po-lines/306857-1_pending_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_awaiting_receipt_physical_checkin-true.json, src/main/resources/data/po-lines/38434-1_pending_fomat-other.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json
[MODORDERS-242](https://issues.folio.org/browse/MODORDERS-242) PoLine FundDistribution schema updates
Adding required `fundId` and updating `code` based on [sample data from mod-finance-storage](https://github.com/folio-org/mod-finance-storage/tree/master/src/main/resources/data/funds)
=> MODORDERS-242 PoLine FundDistribution schema update

src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/purchase-orders/101113_ongoing_pending.json, src/main/resources/data/purchase-orders/306857_ongoing_open.json, src/main/resources/data/purchase-orders/313110_order_without_poLines.json, src/main/resources/data/purchase-orders/38434_ongoing_pending.json, src/main/resources/data/purchase-orders/52590_one-time_pending.json
[MODORDSTOR-98](https://issues.folio.org/browse/MODORDSTOR-98) filterable `boolean` properties should have default value
- pointing to updated acq-models
- setting different values to let filtering work having just sample data
=> MODORDSTOR-98 Schema updates: filterable boolean properties to have default value

pom.xml, src/test/java/org/folio/rest/impl/HelperUtilsTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java
[MODORDSTOR-97](https://issues.folio.org/browse/MODORDSTOR-97) - Randomly failing HelperUtilsTest unit tests
For fixing random HelperUtilsTest fails after migration to junit5.
Migration PowerMockito -> JMockit.
At the present moment JMockit 1.41 is used https://jmockit.github.io/changes.html#1.41 because higher versions require "-javaagent" JVM initialization parameter. Current JMockit functionality is enough for actual tasks. In the future we can consider migrating to more recent versions if needed.
=> MODORDSTOR-97 - Randomly failing HelperUtilsTest unit tests

pom.xml, src/main/java/org/folio/rest/impl/AcquisitionsUnitAssignmentAPI.java, src/main/java/org/folio/rest/impl/OrderLines.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java, src/test/java/org/folio/rest/impl/TestBase.java
[MODORDSTOR-94](https://issues.folio.org/browse/MODORDSTOR-94) Add acquisitions-unit-assignments.recordId to orders views
[MODORDSTOR-95](https://issues.folio.org/browse/MODORDSTOR-95) Add acquisitions-unit-assignments.recordId to poLine views
- Creating `purchase_orders_view` and using it for `GET /orders-storage/purchase-orders` requests
- Creating `po_lines_view` and using it for `GET /orders-storage/po-lines` requests
- Updating `orders_view` and `order_lines_view` to join `acquisitions_unit_assignments` table
- Bonus: updating PO deletion logic to delete acq units assignments and POL number sequence along with order deletion in one transaction
- Does this PR meet or exceed the expected quality …
=> MODORDSTOR-94/95 Add acq unit assignments to orders/lines views

src/main/resources/data/po-lines/14383007-1_awaiting_receipt_gift.json, src/main/resources/data/purchase-orders/268758_one-time_open.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java
Exclude POL tags from PO view, and exclude PO tags from POL view, 
Without this change filtering by tags would check both Purchase Order and Purchase Order Line tags,
and according to comments on [MODORDERS-280](https://issues.folio.org/browse/MODORDERS-280,) PO and POL tags should be searched/filtered separately.
Change views to delete tags before merging PO and POL json objects
=> MODORDERS-280: Change PO and PO line views to avoid collision between tags attributes

descriptors/ModuleDescriptor-template.json, ramls/order-templates.raml, src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/order-templates/order-template.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORDSTOR-106](https://issues.folio.org/browse/MODORDSTOR-106) - Create order-templates API.
Implementation of order templates API according to requirements: https://docs.google.com/spreadsheets/d/1se-a2owRfHLG5eaAZglx4vLvRClCKGp2wZCfD39ZJRY/edit#gid=894044560.
Order templates API implemented, schemas introduced in scope of PR [#182](https://github.com/folio-org/acq-models/pull/182).
=> MODORDSTOR-106 - Create order-templates API

src/main/resources/data/order-templates/amazon_book_orders.json, src/main/resources/data/order-templates/e_books.json, src/main/resources/data/order-templates/e_journal_packages.json, src/main/resources/data/order-templates/german_sound_recordings.json, src/main/resources/data/order-templates/order-template.json, src/main/resources/data/order-templates/our_dissertations.json, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORDSTOR-105](https://issues.folio.org/browse/MODORDSTOR-105) - Populate sample data for Order templates
One need to populate sample data for order templates. Order templates API introduced in [MODORDSTOR-106](https://issues.folio.org/browse/MODORDSTOR-106).
Sample Order Template data tab in this spreadsheet for the 5 sample templates: https://docs.google.com/spreadsheets/d/1N23t8OB0rn0Kl7Qp-09iMW_FnjJYhrDgQUziEetjn8Y/edit#gid=1650451138
One need to coordinate tenant addresses IDs will be implemented in [MODCONF-32](https://issues.folio.org/browse/MODCONF-32).
=> MODORDSTOR-105 - Populate sample data for Order templates

pom.xml, src/main/resources/data/po-lines/101125-1_pending_physical.json
[MODORDSTOR-108](https://issues.folio.org/browse/MODORDSTOR-108) Add qualifier field to `poLine->details->productIds[]`
- Updating the acq-models
- Updating one sample PO line adding product qualifier
- Updating RMB to 25.0.2 (not related to jira requirements)
=> MODORDSTOR-108 Add qualifier field

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
=> MODORDSTOR-123 FOLIO-2358 manage container memory

pom.xml, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
This fixes https://issues.folio.org/browse/MODORDSTOR-161
'Upgrade issue between Q1 and Q2: "public.gin_trgm_ops" does not exist'.
Switch from outdated org.json.JSONObject to io.vertx.core.json.JsonObject
in PurchaseOrderLineNumberTest to avoid another dependency in pom.xml.
=> MODORDSTOR-162: Update to RMB v30.2.3 fixing pg_catalog.pg_trgm

pom.xml
Updating to RMB 30.2.4 fixes https://issues.folio.org/browse/MODORDSTOR-165
(Cannot create POL due to POL limit bug) because it includes
https://issues.folio.org/browse/RMB-673 (totalRecords returns exact hit
count for limit=0).
=> MODORDSTOR-166: Update to RMB 30.2.4 fixing limit=0 totalRecords

src/main/resources/templates/db_scripts/data-migration/10.0.0/po_line_table.sql
[MODORDSTOR-211](https://issues.folio.org/browse/MODORDSTOR-211)
- use `CREATE IF EXIST` instead of `CREATE` to create `uuid-ossp` exstension
- do not drop extension at the end of the script
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MODORDSTOR-211 Cannot enable module for tenant if uuid-ossp extension installed

src/main/java/org/folio/builder/error/NameCodeConstraintErrorBuilder.java, src/main/java/org/folio/builders/error/NameCodeConstraintErrorBuilder.java, src/main/java/org/folio/rest/core/ResponseUtil.java, src/main/java/org/folio/rest/exceptions/ErrorCodes.java, src/main/java/org/folio/rest/impl/AcquisitionsUnitsAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/services/acquisitions/AcquisitionService.java, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/HelperUtilsTest.java
https://issues.folio.org/browse/MODORDSTOR-252
Create BE story to return a more appropriate error code for existing records. Because it's hard to handle it on UI with 'genericError' code. Thanks
{
"errors" : [ {
"message" : "{\n  \"errors\" : [ {\n    \"message\" : \"lower(f_unaccent(jsonb ->> 'name'::text)) value already exists in table acquisitions_unit: test\",\n    \"type\" : \"1\",\n    \"code\" : \"-1\",\n    \"parameters\" : [ {\n      \"key\" : \"lower(f_unaccent(jsonb ->> 'name'::text))\",\n      \"value\" : \"test\"\n    } ]\n  } ]\n}",
"code" : "genericError",
"parameters" : [ ]
} ],
"total_records" : 1
}
Approach : https://github.com/folio-org/mod-finance-storage/pull/110
"errors" : [ {
"message" : "{\"message\":\"Field Name must be …
=> [MODORDSTOR-252] Return readable error on UI if Acquisition unit already exist

src/main/resources/templates/db_scripts/schema.json
[MODORDERS-644](https://issues.folio.org/browse/MODORDERS-644) - Performance Issue: GET API for order-lines is slow
- Removed useless entries in `fullTextIndex`.
- Removed indices for non-existing fields `vendor.vendorAccount`, `vendor.refNumber`.
- Ensured all the fields used in keyword search are in `ginIndex`.
RMB's `likeIndex` is not useful for these queries, we have to use `ginIndex`.
- Are the JIRAs …
=> [MODORDERS-644] Fixed indices for keyword search

Jenkinsfile, README.md
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-orders-storage section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config
Please fix the JSON errors, as described in the subsequent comment.
=> MODORDSTOR-293 FOLIO-3231 Use new api-lint and api-doc CI facilities

src/main/java/org/folio/event/KafkaEventUtil.java, src/main/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandler.java, src/test/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandlerTest.java
https://issues.folio.org/browse/MODORDSTOR-309
There were 3 separate issues fixed to address MODORDSTOR-309
1. Kafka host/port were not configured on https://bulk-edit-perf.ci.folio.org/ for module mod-orders-storage. After add configuration we see that they fetched from secrets as for other modules:
2. x-okapi-tenant has not been populated  in all cases until issues was fixed in scope of PR:
https://github.com/folio-org/mod-data-export-spring/pull/203
3. x-okapi-tenant header comes in lower case, but in order-storage its declared in mixed case like X-Okapi-Tenant. Here is list of headers coming in kafka record:
This particular PR fixes issue this third issue
=> [MODORDSTOR-309] Already exported orders are included repeatedly in next exports

src/main/java/org/folio/services/piece/PieceService.java, src/test/java/org/folio/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
When using P_E_MIX order format OrderLineUpdateInstanceHandler trying to update holdings pieces two times. If one of them(Physical, Eresource) has piece and the other doesn't there will be a problem when updating. The problem would be to create an empty sql query to update pieces.
- Check pieces to emptiness before update
[MODORDERS-749](https://issues.folio.org/browse/MODORDERS-749)
- …
=> [MODORDERS-749] Change instance updates POL details but not UUID and items not appearing

src/main/java/org/folio/rest/persist/HelperUtils.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/services/lines/PoLIneServiceVertxTest.java
Already exported order line contains single quote is included repeatedly in next exports. …
=> [MODORDSTOR-313] - Already exported order line is included repeatedly in next exports.

src/test/java/org/folio/rest/impl/OrdersAPITest.java
https://issues.folio.org/browse/MODORDSTOR-319
*Purpose/Overview:*
Building with JDK 17 fails:
```
[ERROR]   StorageTestSuite$OrdersAPITestNested>OrdersAPITest.testGetPurchaseOrders:141 Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @2ff5659e {code}
```
*Requirements/Scope:*
Replace the method call `field.setAccessible(true)`
*Approach:*
Use JsonObject.mapFrom instead.
*Acceptance criteria:*
Build succeeds under JDK 17
=> MODORDSTOR-319: Replace field.setAccessible(true) for JDK 17

pom.xml, ramls/po-line.raml, ramls/purchase-order.raml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/config/KafkaConfiguration.java, src/main/java/org/folio/event/AuditEventType.java, src/main/java/org/folio/event/ExportEventType.java, src/main/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandler.java, src/main/java/org/folio/event/service/AuditEventProducer.java, src/main/java/org/folio/event/util/KafkaEventUtil.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/verticles/KafkaConsumersVerticle.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/KafkaEventUtilTest.java, src/test/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandlerTest.java, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java, src/test/java/org/folio/rest/impl/TestBase.java
https://issues.folio.org/browse/MODORDSTOR-324 
Currently we use implementation to send event after creating/updating order as 2 separate actions. When we implement transaction outbox pattern - implementation in OrderAPI/ Order Line API will be changed to make it more reliable atomic operation. Integration tests should not be changed after switching to outbox pattern implementation
Tests using shared kafka, to distinquish kafka messages between separate tests userId header is used, each test has unqiue userId header
=> MODORDSTOR-324. Add audit log message schemas and producer for sending these Kafka messages

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/titles.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODORDSTOR-338 Use GitHub Workflows api-lint and api-schema-lint and api-doc

descriptors/ModuleDescriptor-template.json, ramls/po-line-batch.raml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/event/service/AuditOutboxService.java, src/main/java/org/folio/rest/impl/PoLineBatchAPI.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/services/lines/PoLinesBatchService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/PoLineBatchAPITest.java, src/test/java/org/folio/services/lines/PoLinesServiceTest.java
https://issues.folio.org/browse/MODORDSTOR-344
* implemented new endpoint
Unfortunately it was impossible to use batch update for referenced titles due to complicated buissnes logic involved
to avoid breaking the …
=> MODORDERS-344 poline update batch API

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDERS-944
Analyzed use cases and created index for donorOrganizationIds. we assumed it can be used like this query and it involve regular index.
```
orders/composite-orders?query=(donorOrganizationIds==("8a33895e-2c69-4a98-ab48-b7ec1fa852d0" or "aaa541f3-39d2-4887-ab8f-6ba12d08ca52")) sortby metadata.updatedDate/sort.descending
```
logs
```
16:13:42 [825517/orders;849897/orders-storage] [diku] [7b27d828-f9fa-5399-a368-0587f338be7e] [mod_orders_storage] INFO  RestRouting          invoking getOrdersStoragePurchaseOrders
16:13:42 [825517/orders;849897/orders-storage] [diku] [7b27d828-f9fa-5399-a368-0587f338be7e] [mod_orders_storage] INFO  CQL2PgJSON           loadDbSchema: Loaded templates/db_scripts/schema.json OK
16:13:42 …
```
=> [MODORDERS -  944] - Added donorOrganizationIds index 

src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/title/TitleService.java, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java, src/test/java/org/folio/services/title/TitleServiceTest.java
[MODORDSTOR-362](https://issues.folio.org/browse/MODORDSTOR-362) - Inherit claimingActive, claimingInterval from Purchase Order Line to the Receiving Title
Communication …
=> [MODORDSTOR-362] - Title inherited claimingActive, claimingInterval

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/dao/ExtensionRepository.java, src/main/java/org/folio/dao/PieceClaimingRepository.java, src/main/java/org/folio/dao/audit/AuditOutboxEventsLogRepository.java, src/main/java/org/folio/rest/impl/ClaimingAPI.java, src/main/java/org/folio/services/piece/PieceClaimingService.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/ClaimingAPITest.java, src/test/java/org/folio/rest/impl/PiecesAPITest.java, src/test/java/org/folio/rest/impl/TestBase.java
The PR aimed to implement pieces daily based batch job bussiness logic.
Logic to proccess and update piece status was implemented using complex SQL statement which includes:
1. Update using CTE
2. Insert updated rows to audit outbox table
In the end will trigger audit outbox method which will send records to kafka.
[MODORDSTOR-354](https://issues.folio.org/browse/MODORDSTOR-354)
- Do PRs …
=> [MODORDSTOR-354] - Implement business rules to update piece statues in batch job

src/main/java/org/folio/services/title/TitleService.java, src/test/java/org/folio/services/title/TitleServiceTest.java
https://issues.folio.org/browse/MODORDERS-972
When creating title for package order - inherit acq untis from related PO only when title acq units are empty
=> MODORDERS-972. Fixed issue when creating title - acq units not populating

src/main/java/org/folio/services/record/RecordServiceFactoryImpl.java, src/main/resources/META-INF/services/org.folio.service.spi.RecordServiceFactory, src/main/resources/templates/db_scripts/order_templates_table.sql, src/main/resources/templates/db_scripts/po_line_table.sql, src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/CustomFieldsAPITest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-379
This pull request switches the implementation used for `RecordService` from the default `NoOpRecordService` to `RecordServiceImpl`. See the [README](https://github.com/folio-org/folio-custom-fields?tab=readme-ov-file#recordservice) section in [folio-custom-fields](https://github.com/folio-org/folio-custom-fields).
`RecordServiceImpl` ensures that if a user deletes or updates a custom field, these changes will be appropriately reflected in the entities that have values set for this field. Basically, if a custom field is removed it also gets removed from its entities. If a selectable option is removed from a custom field then its entities will no longer have that option selected. 
- Implemented `RecordServiceFactory` to return an …
=> [MODORDSTOR-379] - Manage updates of custom fields through RecordServiceImpl

src/main/resources/templates/db_scripts/schema.json
Adds two additional indexes to mitigate the following warnings when doing a keyword search for orders:
```
WARN  CQL2PgJSON           Doing wildcard LIKE search without index for purchase_order.jsonb->>'dateOrdered', CQL >>> SQL: dateOrdered == "Invalid date*" >>> CASE WHEN length(lower(f_unaccent('Invalid date%'))) <= 600 THEN left(lower(f_unaccent(purchase_order.jsonb->>'dateOrdered')),600) LIKE lower(f_unaccent('Invalid date%')) ELSE left(lower(f_unaccent(purchase_order.jsonb->>'dateOrdered')),600) LIKE left(lower(f_unaccent('Invalid date%')),600) AND lower(f_unaccent(purchase_order.jsonb->>'dateOrdered')) LIKE lower(f_unaccent('Invalid date%')) END
WARN  CQL2PgJSON           Doing wildcard LIKE search without index for purchase_order.jsonb->'metadata'->>'createdDate', CQL >>> SQL: …
```
=> [MODORDSTOR-389] - Address index warnings for table purchase_order

src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/services/lines/PoLinesBatchService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/test/java/org/folio/services/lines/PoLinesServiceTest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-395
Karate PR - https://github.com/folio-org/folio-integration-tests/pull/1319
RMB can populate top level objects, but in code we have an endpoint for PO Line and RMB populates only PO line but not title.
Populate metadata manually for creating Title in endpoint to save Po Line
=> MODORDSTOR-395. Metadata for Create Title is not populated

src/main/java/org/folio/dao/order/OrderDAO.java, src/main/java/org/folio/dao/order/OrderPostgresDAO.java, src/main/java/org/folio/models/TableNames.java, src/main/java/org/folio/rest/impl/PoNumberAPI.java, src/main/resources/templates/db_scripts/data-migration/13.8.0/replace_po_number_sequence.ftl, src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/tables/create_order_number_table.sql, src/test/java/org/folio/rest/impl/PoNumberTest.java
[MODORDSTOR-394](https://folio-org.atlassian.net/browse/MODORDSTOR-394) - PO numbers do not go up consecutively
- Used a table with the last po number used
- Added a script to create the table and a migration script to convert and remove the sequence
Ideally, all the PRs involved in breaking changes …
=> [MODORDSTOR-394] Use a table to generate po numbers

src/main/java/org/folio/rest/impl/RoutingListsAPI.java
[[MODORDSTOR-380] Implement CRUD for Settings API](https://folio-org.atlassian.net/browse/MODORDSTOR-380)
* Generate UUID upon RoutingList creation if it is not present
=>  [MODORDSTOR-364] Generate id if not present when creating routing list

src/main/resources/templates/db_scripts/schema.json
- New Bind Pieces functionally add a new `bindItemId` property on the Piece table, this new property needs a Btree index to improve fetching
- Add RMB-generated `bindItemId` Btree index
=> [MODORDSTOR-PTF-OPT]. Add RMB-generated bindItemId Btree index

src/main/resources/templates/db_scripts/purchase_order_table.sql
- Remove faulty purchase_order_no_acq_unit index thats break installation in older versions of PG DB (v12)
- Remove custom the index from the installation script
=> [MODORDSTOR_IDX_FIX]. Remove faulty purchase_order_no_acq_unit index

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/purchase_order_table.sql
https://folio-org.atlassian.net/browse/MODORDSTOR-413
* Remove faulty purchase_order_no_acq_unit index thats break installation in older versions of PG DB (v12)
Releasing pr https://github.com/folio-org/mod-orders-storage/pull/429
=> Hot Fix Release v13.7.4

pom.xml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/dao/lines/PoLinesDAO.java, src/main/java/org/folio/dao/lines/PoLinesPostgresDAO.java, src/main/java/org/folio/event/InventoryEventType.java, src/main/java/org/folio/event/dto/InventoryFields.java, src/main/java/org/folio/event/dto/ResourceEvent.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/InventoryCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/event/service/AuditOutboxService.java, src/main/java/org/folio/event/util/KafkaEventUtil.java, src/main/java/org/folio/models/ConsortiumConfiguration.java, src/main/java/org/folio/rest/core/ResponseUtil.java, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/services/consortium/ConsortiumConfigurationService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/piece/PieceService.java, src/main/java/org/folio/util/DbUtils.java, src/main/java/org/folio/verticles/InventoryConsumersVerticle.java, src/main/java/org/folio/verticles/InventoryHoldingConsumersVerticle.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/TestUtils.java, src/test/java/org/folio/event/handler/HoldingCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/InventoryCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/services/piece/PieceServiceTest.java
[[MODORDSTOR-416] Add kafka consumer for Holdings Create events with processing logic
](https://folio-org.atlassian.net/browse/MODORDSTOR-416)
- Add inventory consumer verticle and async handler to extend both with item and holding ones
- Add holding event async handler with processing logic
- Add holding consumer verticle 
- Add ConsortiumConfigurationService (same as in mod-orders)
- Fetch pieces and po lines from central tenant in case of ECS
- Update unit tests
=> [MODORDSTOR-416] Add kafka consumer for Holdings Create events with processing logic

src/main/java/org/folio/event/dto/InventoryFields.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/test/java/org/folio/event/handler/HoldingCreateAsyncRecordHandlerTest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-416
During change ownership for Holding user can select another locationId where holding should be created, so we need to update searchLocationIds accordinly.
UI:
How new locationId populated during changing ownership in mod-inventory side:
=> [MODORDSTOR-416]. Update searchLocationId during Holdings Create event

src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/test/java/org/folio/event/handler/HoldingCreateAsyncRecordHandlerTest.java
[[MODORDSTOR-416] Add kafka consumer for Holdings Create events with processing logic
](https://folio-org.atlassian.net/browse/MODORDSTOR-416)
- Fix query parameter for searching PoLines by holdingId
=> [MODORDSTOR-416] Fix PoLine lookup for kafka holding record consumer

pom.xml, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/MockServer.java
[[MODORDSTOR-426] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODORDSTOR-426)
- Update versions
- Add module descriptor validator
=> [MODORDSTOR-426] Update libraries of dependant acq modules to the latest versions

src/main/java/org/folio/event/dto/HoldingEventHolder.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/InventoryCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/InventoryUpdateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemUpdateAsyncRecordHandler.java, src/main/java/org/folio/services/consortium/ConsortiumConfigurationService.java, src/main/java/org/folio/util/HeaderUtils.java, src/test/java/org/folio/event/handler/InventoryUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/services/consortium/ConsortiumConfigurationServiceTest.java, src/test/java/org/folio/util/HeaderUtilsTest.java
- <https://folio-org.atlassian.net/browse/MODORDSTOR-416>
- <https://folio-org.atlassian.net/browse/MODORDERS-1192>
- Holding Create:
- Replace tenant header with central tenant id
- Use the same DB transaction for all operations
- Holding Update:
- Remove central tenant id fetching and usage
- All consumers:
- Replace `.compose()` with `.onComplete()` for all `auditOutboxService.processOutboxEventLogs()` calls 
- Handle `GET /user-tenant` 403 exception with a `.recover()` command
=> [MODORDSTOR-416-6]. Update outbox code to use the same tx

src/main/resources/templates/db_scripts/schema.json
- Replace Title retrieval by `instanceId` via full-text search with an indexed Btree variant
- Logs before index installation:
```log
13:28:25 [454719/orders;350068/orders-storage] [college] [83e561cc-6eec-465c-896e-bfd59efc1cfa] [mod_orders_storage] INFO  RestRouting          invoking getOrdersStorageTitles
13:28:25 [454719/orders;350068/orders-storage] [college] [83e561cc-6eec-465c-896e-bfd59efc1cfa] [mod_orders_storage] INFO  CQL2PgJSON           index titles.jsonb->>'acqUnitIds' generated SQL CASE WHEN length(lower(f_unaccent('[]'))) <= 600 THEN left(lower(f_unaccent(titles.jsonb->>'acqUnitIds')),600) NOT LIKE lower(f_unaccent('[]')) ELSE left(lower(f_unaccent(titles.jsonb->>'acqUnitIds')),600) NOT LIKE left(lower(f_unaccent('[]')),600) OR …
```
=> [MODORDSTOR-PERF]. Add extra btree instanceId index

src/main/java/org/folio/event/dto/ItemFields.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/services/piece/PieceService.java, src/test/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/TestHandlerUtil.java
- <https://folio-org.atlassian.net/browse/MODORDSTOR-427>
- Extract distinct poLine ids from the updated pieces
- Using these distinct poLine ids fetch poLines, and for every fetched poLine fetch all related pieces
- Using all related pieces reconstruct POL locations and searchLocationIds arrays with correct tenantId, holdingId and quantities
- Example unit test output of 2 POL being updated by change item ownership (works in ECS only): 
```log
14:31:45 [] [] [] [] INFO  ItemCreateAsyncRecordHandler updatePieces:: Preparing '3' piece(s) for update processing
14:31:45 [] [] [] [] INFO  ItemCreateAsyncRecordHandler updatePieces:: Updating '3' piece(s), setting receivingTenantId to 'college' and holdingId to '43a5db0d-7852-48dd-8009-98a1e208d874' in centralTenant: 'central'
14:31:45 [] [] [] …
```
=> [MODORDSTOR-427]. PO locations are not changed after updating the item ownership

src/main/java/org/folio/dao/PieceClaimingRepository.java
https://folio-org.atlassian.net/browse/MODORDSTOR-434
Fix SQL error.
Replace `$1` with `$1::text`.
=> MODORDSTOR-434: $1::text fixing "could not determine data type"

README.md, descriptors/ModuleDescriptor-template.json, ramls/pieces-batch.raml, src/main/java/org/folio/dao/PieceClaimingRepository.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/rest/impl/PiecesAPI.java, src/main/java/org/folio/rest/impl/PoLineBatchAPI.java, src/main/java/org/folio/rest/impl/TitlesAPI.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/piece/PieceService.java, src/main/java/org/folio/util/DbUtils.java, src/main/java/org/folio/util/HelperUtils.java, src/main/java/org/folio/util/MetadataUtils.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/PiecesAPITest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/services/piece/PieceServiceTest.java
[[MODORDSTOR-435] Introduce new batch update pieces endpoint](https://folio-org.atlassian.net/browse/MODORDSTOR-435)
- Add new endpoint
- Minor refactoring of PiecesAPI, move certain methods to a service class
=> [MODORDSTOR-435] Introduce new batch update pieces endpoint

src/main/java/org/folio/event/service/AuditEventProducer.java, src/main/java/org/folio/event/service/AuditOutboxService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/service/AuditOutboxServiceTest.java
If only a single event log entity is missing a metadata field, processing halts for all other records
Ensure that metadata field is present before sending kafka event, otherwise throw exception and handle it to keep record processing active
=> Prevent audit outbox processing if an entity has missing metadata

src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/event/dto/ItemEventHolder.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemUpdateAsyncRecordHandler.java, src/main/java/org/folio/services/inventory/OrderLineLocationUpdateService.java, src/main/java/org/folio/util/InventoryUtils.java, src/test/java/org/folio/event/handler/ItemCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemUpdateAsyncRecordHandlerTest.java
[[MODORDERS-1279] After move item in inventory piece Holding ID is updated but POL holding ID is not](https://folio-org.atlassian.net/browse/MODORDERS-1279)
- Create a new service for updating po line location fields after item creation/update
- Update po line location fields in kafka event listeners
- Update tests
=> [MODORDERS-1279] After move item in inventory piece Holding ID is updated but POL holding ID is not

src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/purchase-orders/101101_ongoing_pending.json, src/test/java/org/folio/rest/impl/CustomFieldsAPITest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
- <https://folio-org.atlassian.net/browse/MODORDSTOR-472>
- Remove custom fields from PO and POL sample data
- Exclude custom fields in tenant integration tests
- Update and refactor deprecated methods
- Test locally using the [reinstall endpoint](https://s3.amazonaws.com/foliodocs/api/mgr-tenant-entitlements/s/mgr-tenant-entitlements.html#tag/reinstall/operation/moduleReinstall) that allows to recreate schema objects and reload samples:
```bash
curl --location 'http://localhost:8000/reinstall/modules?tenantParameters=loadReference%3Dtrue%2CloadSample%3Dtrue' \
--header 'Content-Type: application/json' \
--data '{
"tenantId": "10699960-7d5f-4f45-9f4e-b4e0d1a443f1",
"applicationId": "app-combined-1.0.0",
"modules": [
"mod-orders-storage-14.0.0-SNAPSHOT.438"
]
}'
```
- Order template …
=> [MODORDSTOR-472]. Remove custom fields reference data loading

src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/event/dto/HoldingFields.java, src/main/java/org/folio/event/handler/ItemUpdateAsyncRecordHandler.java, src/main/java/org/folio/services/inventory/HoldingsService.java, src/main/java/org/folio/services/inventory/InventoryUpdateService.java, src/main/java/org/folio/util/InventoryUtils.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/handler/ItemUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/services/inventory/HoldingsServiceTest.java, src/test/java/org/folio/services/inventory/InventoryUpdateServiceTest.java
[[MODORDERS-1299] After changing instance in P/E mix order, new instance is not displayed and locations show "Invalid reference"](https://folio-org.atlassian.net/browse/MODORDERS-1299)
- Add holdings service to fetch holding records from inventory storage
- Fetch holdings for item update event handling to determine if independent workflow POLs need locations updated in case of an instance change with holdings being re-created, resulting in existing ones becoming invalid references
- Update existing tests and add new ones
---
=> [MODORDERS-1299] After changing instance in P/E mix order, new instance is not displayed and locations show "Invalid reference"

src/main/java/org/folio/event/handler/ItemUpdateAsyncRecordHandler.java, src/main/java/org/folio/util/HeaderUtils.java
[[MODORDERS-1299] After changing instance in P/E mix order, new instance is not displayed and locations show "Invalid reference"](https://folio-org.atlassian.net/browse/MODORDERS-1299)
Select correct tenant id while fetching holdings
---
=> [MODORDERS-1299] Select correct tenant id while fetching holdings for populating POL locations 

descriptors/ModuleDescriptor-template.json, ramls/titles.raml, src/main/java/org/folio/rest/impl/TitlesAPI.java, src/main/java/org/folio/services/title/TitleService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TitleSequenceNumberTest.java, src/test/java/org/folio/services/title/TitleServiceTest.java, src/test/resources/mockdata/titles/title.json
[[MODORDERS-1356] BE - Create Sequence field in receiving](https://folio-org.atlassian.net/browse/MODORDERS-1356)
- Add new endpoint for generating sequence numbers for pieces
- Implement the endpoint logic and cover with tests
---
=> [MODORDERS-1356] BE - Create Sequence field in receiving

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/lines/PoLinesService.java
[[MODORDERS-1356] Prevent POL update to clear title next sequence number](https://folio-org.atlassian.net/browse/MODORDERS-1356)
- Fix endpoint method
- Add next sequence number to newly created title for comparison
---
=> [MODORDERS-1356] Prevent POL update to clear title next sequence number
