folio-org/mod-orders-storage

CONTRIBUTING.md, LICENSE, NEWS.md, README.md
=> FOLIO-722 tidy 1

src/main/java/org/folio/rest/impl/DetailsAPI.java
the database table is "details" but the code was referencing "detail" singular.
=> table is details not detail

descriptors/ModuleDescriptor-template.json, ramls/orders.raml, src/main/java/org/folio/rest/impl/OrdersAPI.java, src/test/java/org/folio/rest/impl/POTest.java
- added GET /orders to module descriptor
- added orders.raml
- implemented getOrders(...) in OrdersAPI (copy of getPurchaseOrder for now)
=> MODORDSTOR-26 Implement basic GET /orders

src/test/java/org/folio/rest/impl/CostTest.java, src/test/java/org/folio/rest/impl/DetailTest.java, src/test/java/org/folio/rest/impl/VendorDetailTest.java
Merged release branch hot fixes into master
=> Resolved errors with new unit tests

src/test/java/org/folio/rest/impl/AdjustmentsTest.java, src/test/java/org/folio/rest/impl/EresourcesTest.java, src/test/java/org/folio/rest/impl/POLinesTest.java, src/test/java/org/folio/rest/impl/POsTest.java, src/test/java/org/folio/rest/impl/PhysicalsTest.java, src/test/resources/adjustment.sample, src/test/resources/eresource.sample, src/test/resources/physical.sample
Improve unit tests:
https://issues.folio.org/browse/MODORDSTOR-28
Extra work:
- Clean-up existing PLinesTest and POsTest to make it consistent with all remaining tests
Add tests to improve Code Coverage
Add unit tests for existing APIs:
Eresource
Physical
Adjustment
=> MODORDSTOR-28 Improve unit tests

README.md
Change the copywrite year to 2019 as requested by David Crossley
=> changing year to 2019

README.md
The copyright should be for a range (2018 - 2019), not just the most recent year
=> copyright should be for a range

src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java
Resolving [MODORDSTOR-57](https://issues.folio.org/browse/MODORDSTOR-57)
- Using the connection created when transaction started to create an order and sequence
- Dropping the POL number sequence is done after order updated and does not affect result of the update
Call of tenant API without `module_from` and with `loadSample=true`
Call of tenant API with `module_from` and with `loadSample=true`
The database content after both runs of the tenant API from above
- Does this PR meet or exceed the expected quality standards ([sonarcloud PR#86](https://sonarcloud.io/project/issues?id=org.folio%3Amod-orders-storage&pullRequest=86&resolved=false))?
If there are …
=> MODORDSTOR-57 Loading sample data fails

src/main/java/org/folio/rest/persist/EntitiesMetadataHolder.java, src/main/java/org/folio/rest/persist/HelperUtils.java
https://issues.folio.org/browse/MODORDSTOR-55
- Remove references to first and last fields as they are not required
- acq-model PR - https://github.com/folio-org/acq-models/pull/92
- Remove code referencing first and last fields from `getEntitiesCollection`
Ideally all of the PRs involved in breaking changes would be merged in the …
=> MODORDSTOR-55 - remove references to first and last field

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/orders.raml, ramls/po-line.raml, ramls/purchase-order.raml, ramls/receiving-history.raml
[MODORDSTOR-64](https://issues.folio.org/browse/MODORDSTOR-64) Create MODORDSTOR release 4.0.0
- Interface version changes:
* orders-storage.po-lines 4.0
* orders-storage.purchase-orders 4.0
* orders-storage.receiving-history 2.1
- Changes in `raml` files to match interface versions
- News file updated with release details
Ideally all of the PRs involved …
=> MODORDSTOR-64 - Release 4.0.0

descriptors/ModuleDescriptor-template.json, ramls/orders.raml, src/main/java/org/folio/rest/impl/OrdersAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/OrdersAPITest.java
Endpoint updating in addition to PR [#102](https://github.com/folio-org/mod-orders-storage/pull/102).
=> MODORDSTOR-22 - Implement GET /orders w/ search and filtering

README.md, ramls/order-lines.raml, src/main/java/org/folio/rest/impl/OrderLines.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TestBase.java
https://issues.folio.org/browse/MODORDSTOR-73 : Enable search and filtering for /order-lines API
create a new view combining purchase order and PO Line table data.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> MODORDSTOR-73-Search and filtering for order lines

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODORDSTOR-73 -- Adding the permissions required in the module descriptor for the new API endpoint …
=> MODORDSTOR-73: Adding missing permissions

src/main/resources/data/pieces/1a902141-d8c6-4cf3-8a19-193eca007478.json, src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/po-lines/101113-1_pending_physical.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/14383007-1_pending_physical_gift.json, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306251-1_pending_electronic.json, src/main/resources/data/po-lines/306857-1_pending_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_awaiting_receipt_physical_checkin-true.json, src/main/resources/data/po-lines/38434-1_pending_fomat-other.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json, src/main/resources/data/purchase-orders/268758_one-time_open.json
Each record has a unique ID/UUIDs aren't reused
Additionally updated materialType, instanceId and materialSupplier …
=> MODORDSTOR-77 Update ID/UUIDs

pom.xml, src/main/java/org/folio/rest/impl/PiecesAPI.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
* https://issues.folio.org/browse/MODORDSTOR-79
* Implemented described logic
* Unit tests updated …
=> MODORDSTOR-79 Remove associated piece records when removing POLine

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/order-lines.raml, ramls/orders.raml, ramls/po-line.raml, ramls/purchase-order.raml
[MODORDSTOR-87](https://issues.folio.org/browse/MODORDSTOR-87) - Release 6.0.0 
- NEWS.md updating
- Increasing the following interface versions due to non-backward compatible changes in `purchase_order.json` and `po_line.json` (in scope of stories [MODORDSTOR-76](https://issues.folio.org/browse/MODORDSTOR-76), [MODORDSTOR-87](https://issues.folio.org/browse/MODORDSTOR-87)):
- `orders-storage.po-lines`
- `orders-storage.purchase-orders`
mod-orders release [MODORDERS-258](https://issues.folio.org/browse/MODORDERS-258).
- What …
=> MODORDSTOR-87 - Release 6.0.0

descriptors/ModuleDescriptor-template.json, ramls/acquisitions-unit.raml, ramls/order-invoice-relns.raml, src/main/java/org/folio/rest/impl/AcquisitionsUnitAPI.java, src/main/java/org/folio/rest/impl/AcquisitionsUnitsAPI.java, src/main/java/org/folio/rest/impl/OrderInvoiceRelnsAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/acquisitions-unit/acquisitions-unit.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestEntities.java
https://issues.folio.org/browse/MODORDSTOR-82
Implement basic CRUD for acquisitions unit. …
=> MODORDSTOR-82 implement basic CRUD for acquisitions unit

descriptors/ModuleDescriptor-template.json, ramls/acquisitions-unit-assignments.raml, src/main/java/org/folio/rest/impl/AcquisitionsUnitAssignmentAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/acquisitions-unit-assignments/AUA-04ae9da2.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestEntities.java
https://issues.folio.org/browse/MODORDSTOR-92
* ModuleDescriptor, RAML are updated
* Schema and sample data are created
* Implemented CRUD endpoints
* Unit tests are updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> MODORSTOR-92 CRUD for /orders-storage/acquisitions-unit-assignments

pom.xml
[MODORDSTOR-97](https://issues.folio.org/browse/MODORDSTOR-97) - Randomly failing HelperUtilsTest unit tests (in addition to [#133](https://github.com/folio-org/mod-orders-storage/pull/133))
JMockit + JaCoCo integration
pom.xml changes
=> MODORDSTOR-97 - Randomly failing HelperUtilsTest unit tests

src/main/resources/data/acquisitions-units-memberships/acquisition_unit_membership.json, src/main/resources/data/order-invoice-relationships/36547_12345.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306857-1_awaiting_receipt_physical.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_physical_checkin-true.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json
[MODORDERS-247](https://issues.folio.org/browse/MODORDERS-247) Make contributor-name-type configurable
[MODINVOSTO-25](https://issues.folio.org/browse/MODINVOSTO-25) Improve order-invoice sample data
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> MODORDERS-247/MODINVOSTO-25

src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/po-lines/101113-1_pending_physical.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/14383007-1_awaiting_receipt_gift.json, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306857-1_awaiting_receipt_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_physical_checkin-true.json, src/main/resources/data/po-lines/38434-1_pending_fomat-other.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json
https://issues.folio.org/browse/MODORDERS-280
- Update test data
- Update acq-models to latest module …
=> MODORDERS-280- update tags according to schema

src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/po-lines/101113-1_pending_physical.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/14383007-1_awaiting_receipt_gift.json, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306251-1_pending_electronic.json, src/main/resources/data/po-lines/306857-1_awaiting_receipt_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_physical_checkin-true.json, src/main/resources/data/po-lines/38434-1_pending_fomat-other.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json
https://issues.folio.org/browse/MODORDERS-275 - Make poLine.source an enum
Change to use source enum changes
Change mock data
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> MODORDERS-275- Change Source to enum

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/orders.raml, ramls/pieces.raml, ramls/po-line.raml, ramls/purchase-order.raml, ramls/receiving-history.raml, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-101](https://issues.folio.org/browse/MODORDSTOR-101) - mod-orders-storage - Release 7.0.0
**Updated interfaces:** 
- orders-storage.pieces 3.0 -> 3.1
- orders-storage.po-lines 6.0 -> 7.0
- orders-storage.purchase-orders 5.1 -> 6.0
- orders-storage.receiving-history 3.0 -> 3.1
=> MODORDSTOR-101 - Release 7.0.0

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-102 - 
- Remove FK constraint
While it's …
=> MODORDSTOR-102- Removing FK constraint on acq-units-assignments

ramls/acquisitions-unit.raml
Point acquisitions-unit schemas/examples to acquisitions-unit folder with respect to acq-model changes [PR#173](https://github.com/folio-org/acq-models/pull/173)
- Update schemas/examples in raml to point to the acquisitions-unit folder
Needs to be merged along:
acq-model - [PR#173](https://github.com/folio-org/acq-models/pull/173)
mod-orders - [PR#205](https://github.com/folio-org/mod-orders/pull/205)
Point acq-model to latest master after merging PR#173
- Do JIRAs exist to …
=> Update raml to point to acqs-unit schemas/examples in acquisitions-unit folder

src/main/resources/data/purchase-orders/101101_ongoing_pending.json, src/main/resources/data/purchase-orders/101113_ongoing_pending.json, src/main/resources/data/purchase-orders/101125_one-time_pending.json, src/main/resources/data/purchase-orders/14383007_ongoing_open.json, src/main/resources/data/purchase-orders/268758_one-time_open.json, src/main/resources/data/purchase-orders/268879_one-time_closed.json, src/main/resources/data/purchase-orders/306251_one-time_closed.json, src/main/resources/data/purchase-orders/306857_ongoing_open.json, src/main/resources/data/purchase-orders/312325_one-time_open.json, src/main/resources/data/purchase-orders/313000_one-time_open.json, src/main/resources/data/purchase-orders/36547_one_time_closed.json, src/main/resources/data/purchase-orders/S60402_ongoing_closed.json
https://issues.folio.org/browse/MODORDERS-291
Modified sample data
Pointed to latest acq-models …
=> MODORDERS-291- add approval date and id

src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java
https://issues.folio.org/browse/MODORDSTOR-107
* Proper pgclient.execute(...) method used
* Added check on PUT order …
=> MODORDSTOR-107 fixed connection handling. fixed PUT order flow

src/main/resources/data/acquisitions-units/acquisitions-unit.json
[MODORDERS-293](https://issues.folio.org/browse/MODORDERS-293) Acquisition units - soft delete
Just pointing to updated schema and adding new property to sample
=> MODORDERS-293 Acquisition units - soft delete

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/order-lines.raml, ramls/po-line.raml, src/main/resources/data/order-templates/german_sound_recordings.json, src/main/resources/data/po-lines/101101-1_pending_physical_checkin-true.json, src/main/resources/data/po-lines/101113-1_pending_physical.json, src/main/resources/data/po-lines/101125-1_pending_physical.json, src/main/resources/data/po-lines/14383007-1_awaiting_receipt_gift.json, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306251-1_pending_electronic.json, src/main/resources/data/po-lines/306857-1_awaiting_receipt_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/36547-1_physical_checkin-true.json, src/main/resources/data/po-lines/38434-1_pending_fomat-other.json, src/main/resources/data/po-lines/52590-1_pending_physical.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json, src/main/resources/templates/db_scripts/data-migration/po_line_table.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-109](https://issues.folio.org/browse/MODORDSTOR-109) Allow fund distributions to be specified as amount or percentage
- Updating acq-models and samples
- Adding re-runnable script to migrate existing data
- Update each fundDistribution element renaming `percentage` to `value` and adding `distributionType` with `percentage` value
- Limit to only those records which have any `fundDistribution` and are not yet updated
- As this is breaking change, the interface major version is increased
- [DB Schema migration for module update](https://github.com/folio-org/raml-module-builder/blob/master/DB-schema-migration.md)
- The script approach to update each element from array property is based on [How to update complex jsonb column?](https://dba.stackexchange.com/questions/146683/how-to-up …
=> MODORDSTOR-109 Allow fund distributions to be specified as amount or percentage

src/main/resources/data/po-lines/79-1_physical_checkin-true.json, src/main/resources/data/po-lines/81-1_pending_fomat-other.json, src/main/resources/data/purchase-orders/79_one_time_closed.json, src/main/resources/data/purchase-orders/81_ongoing_pending.json
https://issues.folio.org/browse/MODORDERS-334
* adjusted sample data
* merge after https://github.com/folio-org/acq-models/pull/197 …
=> MODORDERS-334 Update purchase order number pattern

src/main/resources/data/order-invoice-relationships/81_81.json
https://issues.folio.org/browse/MODINVOICE-116
* Need to apply the latest schemas (especially receiving_history.json) and adjust sample data 
* pointed acq-models submodule to the latest commit
* adjusted order-invoice-relationships sample
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> MODINVOICE-116 Update purchase order number pattern

pom.xml, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/OrdersAPITest.java
[MODORDSTOR-124](https://issues.folio.org/browse/MODORDSTOR-124) - Update RMB to 28.1.1
In order to improve performance and provide better reliability (at least it is declared by the core team) one need to update RMB version at least to 28.1.1.
1. Migration to RMB 29.0.1, VertX 3.8.1 and AspectJ 1.9.4
2. Future -> Promise
1. It is mandatory to add "auditingTableName": "NOT_EXISTING_AUDITING_TABLE" for table deletion. Not clear. Maybe RMB issue? 
- Do JIRAs exist to update the …
=> MODORDSTOR-124 - Update RMB to 28.1.1

src/main/resources/templates/db_scripts/schema.json
MODORDSTOR-111 Remove outdated indexes on jsonb->>'foreginKeyId' field
Update schema.json per https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-271
=> MODORDSTOR-111 Remove outdated indexes on jsonb->>'foreginKeyId' field

NEWS.md, pom.xml
MODORDSTOR-121 - Release 9.0.0
po-line interface version has already updated to 8.0
=> MODORDSTOR-121 - Release 9.0.0

src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-02_awaiting_receipt_physical.json, src/main/resources/data/po-lines/268758-03_fully_received_electronic_resource.json, src/main/resources/data/po-lines/268879-1_fully_received_electronic.json, src/main/resources/data/po-lines/306857-1_awaiting_receipt_physical.json, src/main/resources/data/po-lines/312325-1_fully_received_electronic_method-purchase_at_vendor_system.json, src/main/resources/data/po-lines/313000-1_awaiting_receipt_mix-format.json, src/main/resources/data/po-lines/79-1_physical_checkin-true.json, src/main/resources/data/po-lines/S60402-80_electronic_receipt_status-absent.json
folio-org/mod-finance-storage#73 sample data consistency …
=> MODFISTO-71 Fix sample data

pom.xml
=> FOLIO-2421 - increment snap version fom 9.1.0 to 10.0.0

src/main/resources/templates/db_scripts/data-migration/10.0.0/po_line_table.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-128](https://issues.folio.org/browse/MODORDSTOR-128)
- for po_line table rename title to titleOrPackage, delete instanceId, add isPackage
- create title for each unprocessed poLine
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> MODORDSTOR-128 Data migration scripts for schema changes

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/resources/data/purchase-orders/101101_ongoing_pending.json, src/main/resources/data/purchase-orders/101113_ongoing_pending.json, src/main/resources/data/purchase-orders/14383007_ongoing_open.json, src/main/resources/data/purchase-orders/306857_ongoing_open.json, src/main/resources/data/purchase-orders/81_ongoing_pending.json, src/main/resources/data/purchase-orders/S60402_ongoing_closed.json, src/main/resources/templates/db_scripts/data-migration/10.0.0/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
https://issues.folio.org/browse/MODORDSTOR-131
* sample data is updated
* data migration scripts are implemented …
=> MODORDSTOR-131 Renewal/subscription PO schema changes

descriptors/ModuleDescriptor-template.json, ramls/configuration.raml, src/main/java/org/folio/rest/impl/ConfigurationAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/configuration/prefixes/prefix.json, src/main/resources/data/configuration/reasons-for-closure/custom_reason.json, src/main/resources/data/configuration/suffixes/suffix.json, src/main/resources/data/system/reasons-for-closure/cancelled.json, src/main/resources/data/system/reasons-for-closure/ceased.json, src/main/resources/data/system/reasons-for-closure/complete.json, src/main/resources/data/system/reasons-for-closure/duplication.json, src/main/resources/data/system/reasons-for-closure/error.json, src/main/resources/data/system/reasons-for-closure/lack_of_funds.json, src/main/resources/data/system/reasons-for-closure/lack_of_use.json, src/main/resources/data/system/reasons-for-closure/licensing_terms.json, src/main/resources/data/system/reasons-for-closure/low_quality.json, src/main/resources/data/system/reasons-for-closure/merged_with_another_titles.json, src/main/resources/data/system/reasons-for-closure/split_into_other_titles.json, src/main/resources/data/system/reasons-for-closure/title_is_out_of_print.json, src/main/resources/data/system/reasons-for-closure/title_received_as_gift.json, src/main/resources/data/system/reasons-for-closure/title_wont_be_published.json, src/main/resources/data/system/reasons-for-closure/title_wont_be_published_this_year.json, src/main/resources/data/system/reasons-for-closure/transferred_to_another_publisher.json, src/main/resources/data/system/reasons-for-closure/unpreffered_format.json, src/main/resources/data/system/reasons-for-closure/unresponsive_vendor.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORDSTOR-119](https://issues.folio.org/browse/MODORDSTOR-119) - Migrate orders settings from mod-configuration
Migrate orders-specific configuration to mod-orders-storage
Create GET, POST, DELETE endpoints for reason-for-closure, prefix, suffix:
- orders-storage/configuration/reasons-for-closure
- orders-storage/configuration/prefixes
- orders-storage/configuration/suffixes
PUT operation is excluded because no need to update trivial instances
- Do …
=> MODORDSTOR-119 - Migrate orders settings from mod-configuration

src/main/resources/data/configuration/prefixes/prefix.json, src/main/resources/data/configuration/suffixes/suffix.json
Follow up for [MODORDSTOR-119](https://issues.folio.org/browse/MODORDSTOR-119) to make prefix/suffix name in sample-data shorter
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> MODORDSTOR-119 Make the prefix/suffix names shorter

src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/utils/IsolatedTenant.java, src/test/java/org/folio/rest/utils/IsolatedTenantExtension.java, src/test/java/org/folio/rest/utils/TestData.java, src/test/java/org/folio/rest/utils/TestEntities.java
- Implementing cascade deletion for Titles once we delete po line
- add cascade deletion for po line
- refactoring of tests for able run it in isolated tenant
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
=> Modordstor 139

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/po-line.raml
Bugfix release 10.0.1 
https://issues.folio.org/browse/MODORDSTOR-142
=> Tmp bugfix 10.0.1

descriptors/ModuleDescriptor-template.json, src/main/resources/data/purchase-orders/suf14383007pref_ongoing_open_with_prefix_and_suffix.json, src/main/resources/templates/db_scripts/data-migration/10.1.0/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/utils/TestEntities.java
[MODORDSTOR-133](https://issues.folio.org/browse/MODORDSTOR-133)
- Add poNumberPrefix and poNumberSuffix fields
- Added poNumberPrefix and poNumberSuffix fields with examples
- Added migration script to set prefix and suffix based on poNumber
- Test data and test updated
Ideally all of the PRs involved in breaking changes would be merged in the same day …
=> Modordstor 133

descriptors/ModuleDescriptor-template.json, ramls/po-line.raml, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/resources/templates/db_scripts/data-migration/10.0.0/po_line_table.sql, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java
https://issues.folio.org/browse/MODORDSTOR-145
* added instanceId to poline schema
* instanceId populated …
=> MODORDSTOR-145 populated instanceId for title

src/main/java/org/folio/rest/impl/PoLinesAPI.java
https://issues.folio.org/browse/MODORDSTOR-145
* title update fixed
While it's helpful …
=> MODORDSTOR-145 title update fixed

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-144
* release notes updated
While it's …
=> release 10.0.2

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/resources/data/po-lines/268758-01_awaiting_receipt_physical.json, src/main/resources/templates/db_scripts/data-migration/11.0.0/update_title.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-136](https://issues.folio.org/browse/MODORDSTOR-136)
- updated title and PoLine schemas
- updated logic of title creation and update upon poLine creation/update to set new fields
- added migration script to update new title's fields (run from version 11.0.0)
- enabled metadata generation for titles table
Ideally all of the PRs involved in …
=> MODORDSTOR-136 Title, PoLine schema updates

src/main/java/org/folio/rest/impl/ConfigurationAPI.java
Update model with encumbrance transaction "Pending"
Update model …
=> [MODORDERS-338] - Update acq-models

pom.xml, src/main/java/org/folio/rest/impl/AbstractApiHandler.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PoNumberAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/Tx.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
[MODORDSTOR-150](https://issues.folio.org/browse/MODORDSTOR-150) - Update to RMB v30.0.2
Update to RMB v30.0.2
RMB and VertX updated …
=> MODORDSTOR-150 - Update to RMB v30.0.2

pom.xml, src/main/java/org/folio/rest/impl/AbstractApiHandler.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PoNumberAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/Tx.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
* revert rmb to 29.0.1 because of troubles with rmb 30.0.2
https://issues.folio.org/browse/RMB-646
* reverted rmb to 29.0.1 …
=> Modordstor 150 - reverted rmb to 29.0.1

pom.xml, src/main/java/org/folio/rest/impl/AbstractApiHandler.java, src/main/java/org/folio/rest/impl/AcquisitionsUnitsAPI.java, src/main/java/org/folio/rest/impl/AlertsAPI.java, src/main/java/org/folio/rest/impl/ConfigurationAPI.java, src/main/java/org/folio/rest/impl/OrderInvoiceRelnsAPI.java, src/main/java/org/folio/rest/impl/OrderLines.java, src/main/java/org/folio/rest/impl/OrderTemplatesAPI.java, src/main/java/org/folio/rest/impl/OrdersAPI.java, src/main/java/org/folio/rest/impl/PiecesAPI.java, src/main/java/org/folio/rest/impl/PoLineNumberAPI.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PoNumberAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/impl/ReceivingHistoryAPI.java, src/main/java/org/folio/rest/impl/ReportingCodesAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/impl/TitlesAPI.java, src/main/java/org/folio/rest/persist/EntitiesMetadataHolder.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/Tx.java, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
https://issues.folio.org/browse/MODORDSTOR-150
* migrate to rmb v30.0.2 with
* descending sort fix
* optimized imports …
=> MODORDSTOR-150 migrate to rmb v30.0.2

src/main/resources/templates/db_scripts/data-migration/11.0.0/update_title.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-153](https://issues.folio.org/browse/MODORDSTOR-153)
- update tiles script has been updated to exclude package name from titles not related to package PO Lines or PO Lines linked to package PO Lines
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MODORDSTOR-153 Package name populated for non-package titles during migration to 11.0.0 version

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-160
* release note are updated
While it's …
=> release 11.0.1

src/main/java/org/folio/rest/impl/PoLinesAPI.java
* updating poline cause promise completion error
* fixed promise completion
While it's …
=> fixed promise completion

NEWS.md, pom.xml
* release 11.0.2
While it's helpful for reviewers to help …
=> MODORDSTOR-163 release 11.0.2

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-167
release 11.0.3
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> Tmp release 11.0.3

Dockerfile, Jenkinsfile, pom.xml, src/test/java/org/folio/rest/impl/HelperUtilsTest.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
https://issues.folio.org/browse/MODORDSTOR-173
* updated rmb and dependencies
* disabled 3 tests because of incompatibility with jdk 11 …
=> MODORDSTOR-173 RMB v31.1.1

pom.xml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/dao/lines/PoLinesDAO.java, src/main/java/org/folio/dao/lines/PoLinesPostgresDAO.java, src/main/java/org/folio/models/CriterionBuilder.java, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/rest/impl/PoLineNumberAPI.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/persist/CriterionBuilder.java, src/main/java/org/folio/rest/persist/DBClient.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/ResponseUtils.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/order/OrderSequenceRequestBuilder.java, src/test/java/org/folio/dao/lines/PoLinesPostgresDAOTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/persist/DBClientTest.java, src/test/java/org/folio/rest/persist/ResponseUtilsTest.java, src/test/java/org/folio/rest/util/RestTestUtils.java, src/test/java/org/folio/rest/util/TestConfig.java, src/test/java/org/folio/rest/util/TestConstants.java, src/test/java/org/folio/services/lines/PoLinesServiceTest.java
https://issues.folio.org/browse/MODORDSTOR-177
1.Refactoring
2.Logic changed …
=> MODORDSTOR-177 - Does not save POL after unopen an orde

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/order-lines.raml, ramls/po-line.raml, ramls/purchase-order.raml
https://issues.folio.org/browse/MODORDSTOR-171
* Updated release notes
While it's …
=> MODORDSTOR-171 Release 11.1.0

pom.xml
=> [MODORDSTOR-186] - Fix logging issue

pom.xml
(cherry picked from commit aa8db83ed2e1e7705ef3ee97fbc506f9aa9ce7af) …
=> [MODORDSTOR-186] - Fix (#207)

NEWS.md, pom.xml
[MODORDSTOR-188](https://issues.folio.org/browse/MODORDSTOR-188) …
=> MODORDSTOR-186 Bugfix release 11.1.1

NEWS.md
Update NEWS.md
While it's helpful for reviewers to help identify potential problems, …
=> MODORDSTOR-188 Update NEWS

pom.xml
https://issues.folio.org/browse/MODORDSTOR-190
*  rmb 31.1.5 …
=> MODORDSTOR-190 rmb 31.1.5

NEWS.md
[MODORDSTOR-191](https://issues.folio.org/browse/MODORDSTOR-191)
MODORDSTOR (mod-orders-storage) Bugfix release …
=> MODORDSTOR-191 mod-orders-storage: Update RMB

NEWS.md, pom.xml
=> Tmp release 11.1.2 to b11.1

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-195
While it's …
=> MODORDSTOR-195 release 11.1.3

NEWS.md
=> MODORDERS-195 news.md -> master

NEWS.md, pom.xml
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> [MODORDSTOR-199] MODORDSTOR (mod-orders-storage) Bugfix release

NEWS.md
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> MODORDSTOR-199 Update news.md

src/main/resources/templates/db_scripts/data-migration/11.0.0/purchase_order_table_1.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-187
Added migration script for "reEncumber" field in the purchase_order table …
=> [MODORDSTOR-187] Added migration script for "reEncumber" field in the purchase_order table

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-116
Schema "poLine" updated with cross-idex …
=> [MODORDSTOR-116] - Use cross-index subqueries instead of views

src/main/resources/templates/db_scripts/data-migration/11.0.0/pol_status_for_ongoing_orders.sql, src/main/resources/templates/db_scripts/schema.json
- https://issues.folio.org/browse/MODORDSTOR-212
Added migration script to update order lines …
=> [MODORDSTOR-212] Fix order line paymentStatus and receiptStatus for ongoing orders

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dao/lines/PoLinesPostgresDAO.java, src/main/java/org/folio/rest/impl/AbstractApiHandler.java, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/rest/impl/PoLineNumberAPI.java, src/main/java/org/folio/rest/impl/PoNumberAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/test/java/org/folio/dao/lines/PoLinesPostgresDAOTest.java, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/PoNumberTest.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java, src/test/java/org/folio/rest/impl/PurchaseOrderLinesApiTest.java, src/test/java/org/folio/rest/impl/PurchaseOrderNumberUniquenessTest.java, src/test/java/org/folio/rest/impl/ReceivingHistoryTest.java, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/util/TestConfig.java, src/test/java/org/folio/rest/utils/IsolatedTenantExtension.java, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java, src/test/resources/log4j2-test.properties 
[MODORDSTOR-205](https://issues.folio.org/browse/MODORDSTOR-205)
mod-orders-storage: Update RMB
While it's helpful for reviewers to help identify potential problems, ensuring that …
=> [MODORDSTOR-205] mod-orders-storage: Update RMB

PERSONAL_DATA_DISCLOSURE.md
=> [MODORDSTOR-208] - Add personal data disclosure form

NEWS.md, pom.xml
… on migration
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
=> MODORDSTOR (mod-orders-storage) Bugfix release

NEWS.md
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
=> [MODORDSTOR-223] MODORDSTOR (mod-orders-storage) Bugfix release

.rancher-pipeline.yml
* Add rancher deployment support from any branch
* added rancher config file
While it's …
=> MODORDERS-448 add rancher deployment support

src/main/resources/data/system/reasons-for-closure/unpreffered_format.json
https://issues.folio.org/browse/MODORDSTOR-227
* fixed typo …
=> MODORDSTOR-227 sample data typo

pom.xml, src/main/java/org/folio/dao/lines/PoLinesPostgresDAO.java, src/main/java/org/folio/rest/impl/AbstractApiHandler.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/rest/impl/PurchaseOrdersAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/ResponseUtils.java, src/test/java/org/folio/dao/lines/PoLinesPostgresDAOTest.java, src/test/java/org/folio/rest/impl/AbstractApiHandlerTest.java, src/test/java/org/folio/rest/impl/PoNumberTest.java, src/test/java/org/folio/rest/impl/SearchOrderLinesTest.java, src/test/java/org/folio/rest/impl/StorageTestSuite.java, src/test/java/org/folio/rest/persist/ResponseUtilsTest.java, src/test/java/org/folio/rest/util/TestConfig.java, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java, src/test/java/org/folio/services/lines/PoLinesServiceTest.java
https://issues.folio.org/browse/MODORDSTOR-218
* RMB update 33.0.0
While it's helpful …
=> MODORDSTOR-218 RMB update 33.0.0

NEWS.md, pom.xml
* https://issues.folio.org/browse/MODORDSTOR-217
While it's …
=> MODORDSTOR-217 release 13.0.0

src/main/java/org/folio/services/migration/MigrationService.java
* https://issues.folio.org/browse/MODORDSTOR-233
The issue reproduces in case if migration data contains single quotes in the name and description fieds of of funds
* replaced single quote with double single quote in json 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MODORDSTOR-233 fixed single quote processing upon migration

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-246
While it's …
=> Tmp release 13.1.0

NEWS.md, pom.xml
Reverts folio-org/mod-orders-storage#268
=> Revert "Tmp release 13.1.0"

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-246
*  updated release notes
While it's …
=> MODORDSTOR-246 release notes 13.1.0 (Kiwi)

src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-255](https://issues.folio.org/browse/MODORDSTOR-255) - Add indexes to improve searching speed of polines
- Added a full text index for `acqUnitIds` to table `purchase_order`
- Added a full text index for `vendorDetail.referenceNumbers` to table `po_line`, including `arraySubfield` and `arrayModifiers` to allow for more precise and performant queries
- Added normal indices in table `acquisition_unit` for `isDeleted` and `protectRead`, for requests from mod-orders.
- To search only reference numbers, queries for po lines with a reference number can be written as
`query=vendorDetail.referenceNumbers=/@refNumber "123456"`
- To be more specific, queries can use a syntax like
`query=vendorDetail.referenceNumbers=/@refNumberType="Vendor title number"/@refNumber "123456"`
or …
=> [MODORDSTOR-255] Added indices for performance

descriptors/ModuleDescriptor-template.json, ramls/acquisition_method.raml, src/main/java/org/folio/rest/impl/AcquisitionMethodAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/data/acquisition-methods/acquisition-method.json, src/main/resources/data/system/acquisition-methods/approval_plan.json, src/main/resources/data/system/acquisition-methods/demand_driven_acquisitions.json, src/main/resources/data/system/acquisition-methods/depository.json, src/main/resources/data/system/acquisition-methods/evidence_based_acquisitions.json, src/main/resources/data/system/acquisition-methods/exchange.json, src/main/resources/data/system/acquisition-methods/free.json, src/main/resources/data/system/acquisition-methods/gift.json, src/main/resources/data/system/acquisition-methods/internal_transfer.json, src/main/resources/data/system/acquisition-methods/membership.json, src/main/resources/data/system/acquisition-methods/other.json, src/main/resources/data/system/acquisition-methods/purchase.json, src/main/resources/data/system/acquisition-methods/purchase_at_vendor_system.json, src/main/resources/data/system/acquisition-methods/technical.json, src/main/resources/templates/db_scripts/data-migration/13.3.0/add_acquisition_method_table.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestData.java, src/test/java/org/folio/rest/utils/TestEntities.java
Add acquisition method API
Creader migration
Added system value in acquisition_method table
Added API
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> [MODORDSTOR-259] - Added acquisition method API

pom.xml
https://issues.folio.org/browse/MODORDSTOR-269
While it's …
=> MODORDSTOR-269. Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
release 13.1.2 Bugfix
While it's helpful for reviewers to help …
=> [MODORDSTOR-269] - release 13.1.2 Bugfix

pom.xml
https://issues.folio.org/browse/MODORDSTOR-270
While it's …
=> MODORDSTOR-270. Juniper R2 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-271
While it's …
=> MODORDSTOR-271. Juniper R2 2021 HF #5 module release

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-273
* increased exactCount value
While it's …
=> MODORDSTOR-273 increased exactCount value

descriptors/ModuleDescriptor-template.json, ramls/export_history.raml, src/main/java/org/folio/rest/impl/OrdersStorageExportHistoryAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/utils/TestData.java, src/test/java/org/folio/rest/utils/TestEntities.java, src/test/resources/mockdata/export-history/99fb699a-cdf1-11e9-a9d9-f2801f1b9aa1.json, src/test/resources/mockdata/export-history/99fb699a-cdf1-11e9-a9d9-f2801f1b9aa2.json, src/test/resources/mockdata/export-history/export_history_collection.json
=> [MODORDSTOR-274] - Create export_history table, schema, API

descriptors/ModuleDescriptor-template.json, ramls/po-line-number.raml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/rest/impl/PoLineNumberAPI.java, src/main/java/org/folio/services/lines/PoLineNumbersService.java, src/main/java/org/folio/services/order/OrderSequenceRequestBuilder.java, src/test/java/org/folio/rest/impl/PurchaseOrderLineNumberTest.java
https://issues.folio.org/browse/MODORDSTOR-222
While it's …
=> MODORDSTOR-222. Make /orders-storage/po-line-number endpoint return list of poLine numbers

descriptors/ModuleDescriptor-template.json
=> [MODORDSTOR-284] - Added Display name, description in permission sets

src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/models/TableNames.java, src/main/java/org/folio/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java, src/main/java/org/folio/orders/lines/update/instance/WithoutHoldingOrderLineUpdateInstanceStrategy.java, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/piece/PieceService.java, src/main/java/org/folio/services/title/TitleService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java, src/test/java/org/folio/services/piece/PieceServiceTest.java, src/test/java/org/folio/services/title/TitleServiceTest.java
=> [MODORDSTOR-299] - Implement PATCH Storage API

pom.xml, src/test/java/org/folio/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java, src/test/java/org/folio/rest/persist/DBClientTest.java
https://issues.folio.org/browse/MODORDSTOR-305
Update versions in pom.xml
While it's …
=> MODORDSTOR-305 - upgrade rmb to 34

NEWS.md, pom.xml
https://issues.folio.org/browse/MODORDSTOR-302
While it's …
=> MODORDSTOR-302 Morning Glory R2 2022 v13.3.0 release notes

NEWS.md, src/main/java/org/folio/event/KafkaEventUtil.java, src/test/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandlerTest.java
https://issues.folio.org/browse/MODORDSTOR-310
Release 2022 R2 Morning Glory Bug Fix 1
=> [MODORDSTOR-310] Release 2022 R2 Morning Glory Bug Fix 1

NEWS.md, src/main/java/org/folio/services/piece/PieceService.java, src/test/java/org/folio/orders/lines/update/OrderLineUpdateInstanceHandlerTest.java
https://issues.folio.org/browse/MODORDSTOR-312
Prepare for 2022 R2 Morning Glory Bug Fix 2 release
=> [MODORDSTOR-312] Prepare for 2022 R2 Morning Glory Bug Fix 2 release

NEWS.md, src/main/java/org/folio/rest/persist/HelperUtils.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/services/lines/PoLIneServiceVertxTest.java
[MODORDSTOR-314] Prepare for Morning Glory R2 2022 v13.3.3 release
=> [MODORDSTOR-314] Prepare for Morning Glory R2 2022 v13.3.3 release

pom.xml, src/test/java/org/folio/rest/utils/TenantApiTestUtil.java
https://issues.folio.org/browse/MODORDSTOR-317
* RMB v35.0.1 upgrade
While it's helpful …
=> MODORDSTOR-317 RMB v35.0.1 upgrade

NEWS.md, pom.xml
=> [MODORDSTOR-320] - Release 13.4.0

NEWS.md, src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java
[MODORDSTOR-322](https://issues.folio.org/browse/MODORDSTOR-322)
=> [MODORDSTOR-322] Module release Morning Glory R2 2022 Hot Fix #1

PULL_REQUEST_TEMPLATE.md, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODORDSTOR-321
The property file and all logging commands have been adjusted. …
=> [MODORDSTOR-321] - Logging Improvement - Configuration

NEWS.md, pom.xml
especially as the number of inter-module and inter-team dependencies increase. …
=> [MODORDSTOR-336] - Release v13.5.0

src/main/resources/templates/db_scripts/schema.json
[MODORDERS-869](https://issues.folio.org/browse/MODORDERS-869) - Optimize rollover lookup for po lines
- Added a new index to search for a `fundId` in a po line's `fundDistribution`
- Removed a useless index
This PR should be reviewed and merged at the same time as [the one in mod-orders](https://github.com/folio-org/mod-orders/pull/745).
- Did you modify …
=> [MODORDERS-869] Changed indices for po line fundDistribution

src/main/resources/templates/db_scripts/schema.json
* https://issues.folio.org/browse/MODORDERS-904
* added gin index in order to allow indexed search by fundDistribution content
Communication is paramount if that is to be …
=> MODORDERS-904 added gin index

.gitignore, Dockerfile, Jenkinsfile, pom.xml, src/main/java/org/folio/dao/audit/AuditOutboxEventsLogRepository.java, src/main/java/org/folio/orders/lines/update/OrderLineUpdateInstanceHandler.java, src/main/java/org/folio/rest/core/BaseApi.java, src/main/java/org/folio/rest/core/ResponseUtil.java, src/main/java/org/folio/rest/exceptions/ExceptionUtil.java, src/main/java/org/folio/services/lines/PoLineNumbersService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/services/piece/PieceService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/dao/lines/PoLinesPostgresDAOTest.java, src/test/java/org/folio/rest/core/ResponseUtilTest.java, src/test/java/org/folio/rest/impl/OrdersAPITest.java, src/test/java/org/folio/rest/impl/PoNumberTest.java, src/test/java/org/folio/rest/impl/ReceivingHistoryTest.java, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
Updated to Java 17 by using these references
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
https://github.com/folio-org/mod-orders/pull/760/files
https://github.com/folio-org/mod-finance-storage/pull/363/files
Ideally, all the PRs involved …
=> [MODORDSTOR-342] - Update to Java 17 mod-orders-storage

pom.xml, src/main/java/org/folio/event/service/AuditEventProducer.java, src/test/java/org/folio/StorageTestSuite.java
especially as the number of inter-module and inter-team dependencies increase. …
=> [MODORDSTOR-346] - Upgrade folio-kafka-wrapper to 3.0.0-SNAPSHOT version

NEWS.md, pom.xml
[MODORDSTOR-352](https://issues.folio.org/browse/MODORDSTOR-352) - mod-orders-storage: module release
especially as …
=> [MODORDSTOR-352] - Release v13.6.0

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDERS-944
especially as the number of inter-module and inter-team dependencies …
=> [MODORDERS - 944] - Added index for donorOrganizationIds

pom.xml, src/test/java/org/folio/rest/impl/HelperUtilsTest.java
https://issues.folio.org/browse/MODORDSTOR-353
especially as the number of inter-module and inter-team dependencies …
=> [MODORDERS-353] - Update RMB and vertx to the latest version

src/main/java/org/folio/rest/impl/PiecesAPI.java
https://issues.folio.org/browse/MODORDSTOR-357
especially as the number of inter-module and inter-team dependencies …
=> [MODORDSTOR-357] - Fix piece id update issue

descriptors/ModuleDescriptor-template.json, ramls/claiming.raml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/rest/impl/ClaimingAPI.java, src/main/java/org/folio/services/piece/PieceClaimingService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/ClaimingAPITest.java
especially as the number of inter-module and inter-team dependencies increase. …
=> [MODORDSTOR-356] - Initial setup of claiming batch job

src/main/java/org/folio/services/lines/PoLinesService.java
It is addition to the previous https://github.com/folio-org/mod-orders-storage/pull/366 PR
=> MODORDSTOR-362. Delete unnecessary check

src/main/java/org/folio/services/lines/PoLinesService.java
[MODORDSTOR-362](https://issues.folio.org/browse/MODORDSTOR-362) - Inherit claimingActive, claimingInterval from Purchase Order Line to the Receiving Title
Communication …
=> [MODORDSTOR-362] - Check updated

src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-363
=> MODORDSTOR-363. Add indexes to improve Get Order/Get Po Line/Open Order/Receive order flow

src/main/resources/templates/db_scripts/data-migration/13.7.0/copy_acq_unit_ids_from_order_to_title.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-359](https://issues.folio.org/browse/MODORDSTOR-359) - Create migration script to copy exisitng acqUnitIds from Order to Title
Communication is paramount if …
=> [MODORDSTOR-359] - Added script for updating the acqUnitIds in the title

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/rest/impl/CustomFieldsPostDeployVerticle.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/services/user/NoOpUserService.java, src/main/resources/data/custom-fields/custom-field-po.json, src/main/resources/data/custom-fields/custom-field-pol.json, src/main/resources/data/po-lines/52590-1_pending_pe_mix.json, src/main/resources/data/purchase-orders/52590_one-time_pending.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/CustomFieldsAPITest.java, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestData.java, src/test/java/org/folio/rest/utils/TestEntities.java
This PR integrates the custom fields functionality for purchase orders and purchase order lines. See [MODORDERS-964](https://issues.folio.org/browse/MODORDERS-964). …
=> [MODORDERS-964] Integrate custom fields for purchase orders and purchase order lines

src/main/resources/templates/db_scripts/data-migration/13.7.0/piece_caption_migration.sql, src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODORDSTOR-369
Added migratrion script to update corresponding jsonb in DB. …
=> [MODORDSTOR-369] - Create migration script to change "caption" to "Display summary" for pieces

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/config/ApplicationConfig.java, src/main/java/org/folio/dao/PieceClaimingRepository.java, src/main/java/org/folio/rest/impl/ClaimingAPI.java, src/main/java/org/folio/rest/impl/PiecesAPI.java, src/main/java/org/folio/services/configuration/TenantLocaleSettingsService.java, src/main/java/org/folio/services/piece/PieceClaimingService.java, src/test/java/org/folio/TestUtils.java, src/test/java/org/folio/rest/impl/ClaimingAPITest.java, src/test/java/org/folio/rest/impl/MockServer.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/util/TestConfig.java, src/test/resources/mockdata/configurations.entries/config_default.json, src/test/resources/mockdata/configurations.entries/config_empty.json
[MODORDERS-1011](https://folio-org.atlassian.net/browse/MODORDERS-1011)
especially as the number of inter-module and …
=> [MODORDERS-1011] - Adjust processing of scheduled claiming job to use user's timezone

src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODORDSTOR-387
=> MODORDSTOR-387. Add missed indexes for common operations with orders

pom.xml
https://folio-org.atlassian.net/browse/MODORDSTOR-385
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
=> [MODORDSTOR-385] Upgrade RAML Module Builder

pom.xml
Upgrade to the latest folio-di-support
https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0
Release notes: https://github.com/folio-org/folio-di-support/blob/v2.1.0/doc/RELEASE_NOTES.md
=> MODORDSTOR-385. Upgrade folio di support

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODORDSTOR-390 …
=> [MODORDSTOR-390] - Release v13.7.0

descriptors/ModuleDescriptor-template.json, ramls/routing-list.raml, src/main/java/org/folio/models/TableNames.java, src/main/java/org/folio/rest/impl/RoutingListsAPI.java, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/tables/create_routing_list_table.sql, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java, src/test/java/org/folio/rest/utils/TestData.java, src/test/java/org/folio/rest/utils/TestEntities.java, src/test/resources/mockdata/routing-lists/c0d13648-347b-4ac9-8c2f-5bc47248b871.json
[MODORDSTOR-364: Create routing_list table and API for it](https://folio-org.atlassian.net/browse/MODORDSTOR-364)
* Add a new table schema for routing lists
* Add to acq models: RoutingList, RoutingListCollection
* Add API for all CRUD operations
=> [MODORDSTOR-364] Create routing_list table and API for it

src/main/resources/templates/db_scripts/schema.json
[[MODORDSTOR-396] Add indexes to satisfy filtering by metadata fields](https://folio-org.atlassian.net/browse/MODORDSTOR-396)
Made for:
[MODORDERS-1085. Add ability to search by location and holding in POL](https://folio-org.atlassian.net/browse/MODORDERS-1085)
=> [MODORDSTOR-396] Add indexes to satisfy filtering by metadata fields

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/PoLinesAPI.java, src/main/java/org/folio/services/lines/PoLinesBatchService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/services/lines/PoLinesServiceTest.java
especially as the number of inter-module and inter-team dependencies increase. …
=> Bug Fix Release v13.7.1

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODORDSTOR-399
=> MODORDSTOR-399. Missing interface dependencies in module descriptor

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
Release Q v13.7.2 with missed interfaces in module descriptor
https://folio-org.atlassian.net/browse/MODORDSTOR-399
=> Release Q v13.7.2 with missed interfaces in module descriptor

README.md
https://folio-org.atlassian.net/browse/MODORDSTOR-393
Updating acq-modules to include changes for Title
=> Update acq-models to include boundItemIds field in Title

src/main/java/org/folio/rest/impl/RoutingListsAPI.java
[[MODORDSTOR-364] Create routing_list table and API for it](https://folio-org.atlassian.net/browse/MODORDSTOR-364)
- Remove ID field as required
=> [MODORDSTOR-364] Remove ID as required field from Routing Lists

src/main/resources/templates/db_scripts/po_line_table.sql, src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json
[MODORDSTOR-406](https://folio-org.atlassian.net/browse/MODORDSTOR-406) - Investigate way to improve performance of Orders filtering
Added 4 indices to speed up queries. They can be added by hand to existing Poppy and Quesnelia environments. See the ticket comments for details of the investigation.
TODO: [MODORDSTOR-407](https://folio-org.atlassian.net/browse/MODORDSTOR-407)
- Do PRs exist …
=> [MODORDSTOR-406] Added new indices to speed up filtering from UI

src/main/resources/templates/db_scripts/po_line_table.sql, src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/title_table.sql
[MODORDSTOR-409](https://folio-org.atlassian.net/browse/MODORDSTOR-409)
=> MODORDSTOR-409. Indexes to speedup performance of filtering in Receiving

NEWS.md, pom.xml, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/resources/templates/db_scripts/po_line_table.sql, src/main/resources/templates/db_scripts/purchase_order_table.sql, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/title_table.sql, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/TenantReferenceDataTest.java
Release Quesnelia Service Patch 1 changes that includes the following tickets:
* [MODORDSTOR-406](https://folio-org.atlassian.net/browse/MODORDSTOR-406) - Improve performance of Orders filtering
* [MODORDSTOR-409](https://folio-org.atlassian.net/browse/MODORDSTOR-409) - Improve performance of Receiving filtering
* [MODORDSTOR-408](https://folio-org.atlassian.net/browse/MODORDSTOR-408) - Upgrading tenant resets reference and sample records
=> Release v13.7.3 for Quesnelia Service Patch 1

src/main/resources/templates/db_scripts/data-migration/13.8.0/populate_search_locations_ids.ftl, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/resources/inventory_schema.sql
https://folio-org.atlassian.net/browse/MODORDSTOR-401
Added corresponding migration script.
especially as the number …
=> [MODORDSTOR-401] - Create migration to populate Holding::permanentLocationId

src/main/resources/templates/db_scripts/schema.json
- Update `exactCount` to display a more precise Records count during filtering of large datasets
- Set `exactCount` from 40k to 50k (to align with the value set in mod-invoice-storage)
=> [MODORDSTOR-PTF-OPT-2]. Update exactCount

src/main/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandler.java, src/main/java/org/folio/rest/impl/PoLineBatchAPI.java, src/main/java/org/folio/services/lines/PoLinesBatchService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/test/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandlerTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1192>
- Add titles update for each updated POL
=> [MODORDERS-1192-2]. Add necessary titles update

src/main/java/org/folio/dao/RepositoryConstants.java, src/main/java/org/folio/services/inventory/InventoryUpdateService.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/util/HelperUtils.java, src/main/java/org/folio/util/ResourcePath.java, src/test/java/org/folio/services/inventory/InventoryUpdateServiceTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1192>
- Holding fetching perf improvements
- <https://github.com/folio-org/mod-orders-storage/pull/437>
- <https://github.com/folio-org/mod-orders-storage/pull/440>
- <https://github.com/folio-org/mod-orders-storage/pull/441>
=> [MODORDERS-1192-IMP]. Holding fetching perf improvements

src/main/java/org/folio/event/dto/HoldingEventHolder.java, src/main/java/org/folio/event/dto/HoldingFields.java, src/main/java/org/folio/event/dto/InstanceFields.java, src/main/java/org/folio/event/dto/ItemEventHolder.java, src/main/java/org/folio/event/dto/ItemFields.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/services/inventory/InventoryUpdateService.java, src/main/java/org/folio/util/InventoryUtils.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/handler/HoldingCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/services/inventory/InventoryUpdateServiceTest.java, src/test/java/org/folio/util/InventoryUtilsTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1192>
- Add POL product ids update without normalization or validation (implementation TBD)
- <https://github.com/folio-org/mod-orders-storage/pull/437>
- <https://github.com/folio-org/mod-orders-storage/pull/440>
- <https://github.com/folio-org/mod-orders-storage/pull/441>
- <https://github.com/folio-org/mod-orders-storage/pull/443>
- <https://github.com/folio-org/mod-orders-storage/pull/444>
=> [MODORDERS-1192-5]. Add POL product ids update without validation & normalization

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102 …
=> Release v13.8.0 

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODORDSTOR-432
=> [MODORDSTOR-432] - Missing interface dependencies in module descriptor

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODORDSTOR-432 …
=> Bug Fix Release 13.8.1

NEWS.md, pom.xml, src/main/java/org/folio/dao/PieceClaimingRepository.java
Release Ramsons Bug Fix v13.8.3 that includes fix for https://folio-org.atlassian.net/browse/MODORDSTOR-434
=> Ramsons 13.8.3 Bug Fix

src/main/java/org/folio/event/dto/ResourceEvent.java
- <https://folio-org.atlassian.net/browse/MODINVSTOR-1322>
- Add `eventId` and `eventTs` fields to `ResourceEvent`
- Annotate `ResourceEvent` with `@JsonIgnoreProperties(ignoreUnknown = true)` to ignore new non-ignorable fields
=> [MODINVSTOR-1322]. Extend domain events - update ResourceEvent with new fields

src/main/java/org/folio/rest/impl/PoLinesAPI.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1227>
- Add `id` logging back at 3 locations on PUT and PATCH method in the class
=> [MODORDERS-1227]. Update PoLinesAPI log markers for PUT and PATCH methods

src/main/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandler.java, src/main/java/org/folio/event/handler/HoldingCreateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandler.java, src/main/java/org/folio/event/handler/ItemCreateAsyncRecordHandler.java, src/main/java/org/folio/services/lines/PoLinesService.java, src/main/java/org/folio/util/MetadataUtils.java, src/test/java/org/folio/event/handler/EdiExportOrdersHistoryAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/HoldingCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandlerTest.java, src/test/java/org/folio/event/handler/ItemCreateAsyncRecordHandlerTest.java, src/test/java/org/folio/services/lines/PoLIneServiceVertxTest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-436 …
=> [MODORDSTOR-436] - Populate metadata for entities batch operations

descriptors/ModuleDescriptor-template.json, ramls/pieces-batch.raml, src/main/java/org/folio/rest/impl/PiecesAPI.java, src/main/java/org/folio/services/piece/PieceService.java, src/test/java/org/folio/rest/impl/PiecesAPITest.java, src/test/java/org/folio/services/piece/PieceServiceTest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-438 …
=> [MODORDERSTOR-438] - Implement Create Batch Pieces API

Dockerfile, Jenkinsfile, pom.xml
[[FOLIO-4211] Update to mod-orders-storage Java 21](https://folio-org.atlassian.net/browse/FOLIO-4211)
Update java and dependency versions
=> [FOLIO-4211] Update to mod-orders-storage Java 21

NEWS.md, pom.xml
https://folio-org.atlassian.net/browse/MODORDSTOR-441 …
=> Release v13.8.0

NEWS.md, pom.xml, src/main/java/org/folio/event/service/AuditEventProducer.java, src/main/java/org/folio/event/service/AuditOutboxService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/service/AuditOutboxServiceTest.java
folio-org.atlassian.net/browse/MODORDSTOR-450
especially as the number of inter-module and inter-team dependencies …
=> Bug Fix Release v13.9.2

descriptors/ModuleDescriptor-template.json, src/main/resources/data/po-lines/52590-1_pending_pe_mix.json, src/main/resources/templates/db_scripts/data-migration/14.0.0/change_userlimit_to_string.ftl, src/main/resources/templates/db_scripts/schema.json, src/test/resources/mockdata/po-lines/52590-1_pending_pe_mix_non_package.json, src/test/resources/mockdata/po-lines/52590-1_pending_pe_mix_non_package_with_not_existed_package_poline.json, src/test/resources/mockdata/po-lines/52590-1_pending_pe_mix_non_package_with_package_po_line_id.json, src/test/resources/mockdata/po-lines/52590-1_pending_pe_mix_package.json
[MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
- Schema update
- Migration script
- Resources and test updates
- New API version for `po-lines`
- [acq-models](https://github.com/folio-org/acq-models/pull/519)
- [mod-orders](https://github.com/folio-org/mod-orders/pull/1104)
- [mod-gobi](https://github.com/folio-org/mod-gobi/pull/252)
- [mod-invoice](https://github.com/folio-org/mod-invoice/pull/532)
- [mod-ebsconet](https://github.com/folio-org/mod-ebsconet/pull/96)
- [folio-export-common](https://github.com/folio-org/folio-export-common/pull/92)
- [mod-data-export-worker](https://github.com/folio-org/mod-data-export-worker/pull/649) (uses folio-export-common)
- …
=> [MODORDSTOR-448] Change type of eresource.userLimit to string

src/main/resources/templates/db_scripts/data-migration/13.8.0/pieces_add_isBound.sql, src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODORDSTOR-453
- Add migration script to fix
especially as the number of …
=> [MODORDSTOR-453] - Existing pieces are not displayed in Receiving due to the absence of the isBound flag.

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/data-migration/13.8.0/pieces_add_isBound.sql, src/main/resources/templates/db_scripts/schema.json
https://folio-org.atlassian.net/browse/MODORDSTOR-453 …
=> Bug Fix Release v13.9.3

NEWS.md, pom.xml, src/main/java/org/folio/event/service/AuditEventProducer.java, src/main/java/org/folio/event/service/AuditOutboxService.java, src/main/resources/templates/db_scripts/data-migration/13.8.0/pieces_add_isBound.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/event/service/AuditOutboxServiceTest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-453 …
=> Bug Fix Release v13.8.4

pom.xml
https://folio-org.atlassian.net/browse/FCFIELDS-62 contains some fixes to remove sql injection and java 21 upgrades, use the latest version of this library
=> FCFIELDS-62. Update to the freshest version of  folio-cusom-fields

src/main/java/org/folio/orders/lines/update/instance/WithHoldingOrderLineUpdateInstanceStrategy.java
- <https://folio-org.atlassian.net/browse/MODORDSTOR-458>
- TODO
=> [MODORDSTOR-458]. Invalid reference is displayed in PO line after changing instance connection for the P/E mix order

pom.xml, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/WrapperPiecesAPITest.java
https://folio-org.atlassian.net/browse/MODORDSTOR-452
=> MODORDSTOR-452. Replace net.mguenther.kafka:kafka-junit (EOL)

pom.xml
https://folio-org.atlassian.net/browse/MODORDSTOR-469
Update `folio-custom-fields` to latest version. Fixes https://folio-org.atlassian.net/browse/FCFIELDS-68.
=> [MODORDSTOR-469] Update `folio-custom-fields` dependency

src/main/java/org/folio/services/lines/PoLinesService.java
[[MODORDERS-1356] Update title's next sequence number when updating POL](https://folio-org.atlassian.net/browse/MODORDERS-1356)
Update title's next sequence number when updating POL
---
=> [MODORDERS-1356] Update title's next sequence number when updating POL

src/main/java/org/folio/services/setting/SettingService.java
_Explain why these changes are needed and link the related issue (e.g., https://folio-org.atlassian.net/browse/PROJ-123)._
_Provide a brief technical summary of the changes._
---
=> MODGOBI-232. Decrease settings cache size from 5 min to 1 min

NEWS.md, pom.xml, src/main/java/org/folio/event/handler/HoldingUpdateAsyncRecordHandler.java, src/main/resources/templates/db_scripts/schema.json
Prepare for Sunflower 13.9.5 release that includes fix 
https://folio-org.atlassian.net/browse/MODORDSTOR-483
=> Sunflower release v13.9.5
